version: '2'

services:
  nginx:
    # build: Dockerfiles
    build:
      context: ./nginx_centos
      dockerfile: Dockerfile_alt
      args:
        lien: http://www.brainjar.com/java/host/test.html 
        lol: /usr/share/nginx/html/index.html
    container_name: nginx_centos_ontainer
    ports:
      - 8000:80